name: "Perform a code test"
description: "Installing dependenncies an running a test"

inputs:
   token:
     description: "Token needed to access files "
     required: true
   path:
     description: "Path to test files"
     required: true

runs:
   using: "composite"
   steps:
       - name: Install Python 3
         uses: actions/setup-python@v1
         with:
           python-version: 3.7
       - name: Install dependencies
         shell: bash
         env:
           GITHUB_TOKEN: ${{inputs.token}}
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt --use-deprecated=legacy-resolver
       - name: Run Tests
         shell: bash
         run: python -m unittest discover ${{inputs.path}}
