name: "Perform a code test"
description: "Installing dependencies and running tests"

inputs:
   token:
     description: "Token needed to access files "
     required: true
   path:
     description: "Path to test files"
     required: true
   discover:
     description: "True if the repository supports discover tests command"
     required: false
   test-file-name:
     description: "Test file name, only needed if the repository does not use discover tests command"
     required: false
runs:
   using: "composite"
   steps:
       - name: Install Python 3.11
         uses: actions/setup-python@v5
         with:
           python-version: 3.8
       - name: Install dependencies
         shell: bash
         env:
           GITHUB_TOKEN: ${{inputs.token}}
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run Tests
         shell: bash
         run: |
             if [ -n "${{inputs.discover}}" ]; then
                 python -m unittest discover ${{inputs.path}}
             else
               cd ${{inputs.path}}
               python -m unittest ${{inputs.test-file-name}}
             fi
