name: Node.js CI

inputs:
   node-version:
     description: "Node version to check"
     required: true

runs:
   using: "composite"
   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - run: npm install 
      shell: bash

    - run: npm run test
      shell: bash

    - run: npm run lint
      shell: bash

