name: "Perform a code test"
description: "Installing dependenncies an running a test"

inputs:
   token:
     description: "Token needed to access files "
     required: true
runs:
   using: "composite"
   steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - name: Install dependencies
        shell: bash
        run: |
          npm install 
          npm run compile
      - name: Run Tests
        shell: bash
        run: |
          cd spec
          npm run test
